### ISSUE TITLE
Show user-defined properties (feature request)

### ISSUE THREAD

**Issue by pdonahue-ventana** [SystemRDL/RALBot-html#12]
Would it be possible to display user properties in the HTML output?  Presumably, those properties are interesting and useful enough that the user specified them so it would be nice to have them in the HTML documentation.  It would be nice to have a way to filter which properties end up in the HTML to allow building HTML documentation for different audiences.

It seems that user-defined properties for fields might not fit well in the table.  Maybe they would be more appropriate down where the "desc" field is shown.

**Comment by amykyta3** [comment]
I can see how that would be useful.

I can make it a configurable option where the user of this tool can provide a list of properties to emit to the document, not limited to UDPs.

**Comment by pdonahue-ventana** [comment]
Fantastic!  Thanks.

**Comment by amykyta3** [comment]
Implemented!
Give it a try by installing via:
```
python3 -m pip install --user git+https://github.com/SystemRDL/RALBot-html.git
```
The exporter constructor has a new `extra_doc_properties` argument in its constructor where you can list your UDPs (or any other property you want explicitly shown in the docs)

Let me know if it looks OK and I'll include in the next release.

**Comment by pdonahue-ventana** [comment]
Sorry for the delayed response but I checked it out and it looks good.  I see that you released so we're all set.  Thanks.
