### ISSUE TITLE
Show multiple address maps

### ISSUE THREAD

**Issue by RasmusGOlsen** [SystemRDL/RALBot-html#13]
I wish you will add support for multiple elaborated address maps in the generated HTML left menu.

example
```
-map1
    +sub
+map2
+map3
```

**Comment by amykyta3** [comment]
Are all the address maps part of the same device's address space? If so, join them together with a single top-level address map:
```
addrmap map1_t {
    // ...
};

addrmap map2_t {
    // ...
};

addrmap map3_t {
    // ...
};

addrmap top {
    map1_t map1 @ 0x0000;
    map2_t map2 @ 0x4000;
    map3_t map3 @ 0x8000;
};
```

**Comment by RasmusGOlsen** [comment]
It is the same device, but the address maps are not part of the same address space.
fx. the first address map specifies an address, data, control, and status register to access the second address map, meaning there is no direct access to the second map. I don't know how to specify this in any other way than just having two separate memory spaces.

**Comment by amykyta3** [comment]
Fixed a few navigation and search issues. merged.
Thanks!
