### ISSUE TITLE
Replace decoded number with enum name (feature request)

### ISSUE THREAD

**Issue by kevbroch** [SystemRDL/RALBot-html#4]
If a field has an enumerated encoding, replace the number with the enum name.

**Comment by amykyta3** [comment]
Finally got around to implementing this.
See the example: https://systemrdl.github.io/RALBot-html/?p=turbo_encab.grammeter%5B0%5D.status#state
... or test it out on your end by installing via:
```
python3 -m pip install --user git+https://github.com/SystemRDL/RALBot-html.git
```
Let me know if there are any quirks I missed.
I have a few other features to add so I'll roll them all into the next release.

**Comment by kevbroch** [comment]
Just took it for a spin on our systemRDL files.  Tested changing radix representation, changing dropdown for enum field (and other radix representations) and changing the fully encoded value.  All worked and looked flawless! 

Looks great!  Thank you.  I really appreciate this work.
